[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "remarc"
version = "0.3.1"
description = "Reinforcement-learning based Evolutionary Markovian Resistance Control"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy~=1.26.4",
    "pandas~=2.3.1",
    "scipy~=1.16.0",
    "matplotlib~=3.10.3",
    "torch~=2.7.1",
    "tianshou~=1.2.0",
    "tqdm~=4.67.1",
    "gymnasium~=0.28.1",
    "networkx~=3.5",
    "plotly>=6.6.0",
    "streamlit>=1.30.0",
    "pymdptoolbox>=4.0b3",
    "setuptools<71",
    "optuna>=4.9.0",
]

[project.optional-dependencies]
test = [
    "pytest~=8.4.1",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["remarc*"]

[tool.pyright]
autoSearchPaths = false
extraPaths = ["."]

[tool.pytest.ini_options]
pythonpath = ["."]

